### ISSUE TITLE
Fetch-Reach Result not running

### ISSUE THREAD

**Issue by MishaLaskin** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#12]
Looks like there may be a commit missing for the FetchReach result. When I run it I get

`KeyError: 'linear_hidden_units'`

When I add the hyperparameter manually, an assertion error comes up

`AssertionError: X should be a 2-dimensional tensor`

**Comment by p-christ** [comment]
thanks a lot for pointing this out. I think i've fixed this now, try cloning the latest version and seeing if it works?

**Comment by MishaLaskin** [comment]
Works now! Thanks for the prompt response!
