### ISSUE TITLE
Results.X.py missing correct import path for Trainer

### ISSUE THREAD

**Issue by crashmatt** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#14]
importing Training with
from Trainer import Trainer

fails when running under eclipse pipenv 

To be consistent wtih other imports modify to
from Agents.Trainer import Trainer

**Comment by p-christ** [comment]
thanks i have changed this now

**Comment by crashmatt** [comment]
Found many more like this.  Might make a pull request for it all.
