### ISSUE TITLE
An question about the actor loss calculation in `SAC_Discrete.py`.

### ISSUE THREAD

**Issue by ChangyWen** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#21]
Hi, thank you for your great work, it really helps a lot! I am wondering if you forgot to multiply the `log_action_probabilities` by `self.alpha` in [`line 83 of SAC_Discrete.py`](https://github.com/p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch/blob/77c47fa4510242b302b11f5f617823d45c9da258/agents/actor_critic_agents/SAC_Discrete.py#L83), which, I believe, should be revised as follow:
```
inside_term = self.alpha * log_action_probabilities - min_qf_pi
```
Please correct me if I am wrong about it.

Btw, could you please explain why should we calculate the SAC actor loss in discrete action situation as what you do in [`calculate_actor_loss`](https://github.com/p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch/blob/77c47fa4510242b302b11f5f617823d45c9da258/agents/actor_critic_agents/SAC_Discrete.py#L77) of SAC_Discrete.py, to be more specifically, why should we multiply the inside_term described above by `action_probabilities`?

Thank you very much.

**Comment by ChangyWen** [comment]
> Hi, thank you for your great work, it really helps a lot! I am wondering if you forgot to multiply the `log_action_probabilities` by `self.alpha` in [`line 83 of SAC_Discrete.py`](https://github.com/p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch/blob/77c47fa4510242b302b11f5f617823d45c9da258/agents/actor_critic_agents/SAC_Discrete.py#L83), which, I believe, should be revised as follow:
> 
> ```
> inside_term = self.alpha * log_action_probabilities - min_qf_pi
> ```
> 
> Please correct me if I am wrong about it.
> 
> Btw, could you please explain why should we calculate the SAC actor loss in discrete action situation as what you do in [`calculate_actor_loss`](https://github.com/p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch/blob/77c47fa4510242b302b11f5f617823d45c9da258/agents/actor_critic_agents/SAC_Discrete.py#L77) of SAC_Discrete.py, to be more specifically, why should we multiply the inside_term described above by `action_probabilities`?
> 
> Thank you very much.

**Comment by ChangyWen** [comment]
OK, I suddenly found out why we should multiply the inside_term by the `action_probabilities`.
However, I still think that the `inside_term` should be calculated by the way I described above.

**Comment by p-christ** [comment]
thanks a lot, i think you are correct and i will update it
