### ISSUE TITLE
Problems running the A3C algorithm

### ISSUE THREAD

**Issue by christofer-f** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#22]
Hi and thanks for a great repo!

I have some problems running the A3C algorithm in Cart_Pole.py

I get the error:
...pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

pytorch\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Do you know what can be the problem?

Br,
Christofer

**Comment by christofer-f** [comment]
This issue can be closed. PyTorch multiprocessing doesn't play nice with the GPU

**Comment by shuferhoo** [comment]
I have the same problem with you，do you have slove the problem?
