### ISSUE TITLE
Additional `critic_target gather` in SAC_discrete.py 

### ISSUE THREAD

**Issue by YunqiuXu** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#25]
I found there's an additional gather operation in 

https://github.com/p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch/blob/master/agents/actor_critic_agents/SAC_Discrete.py#L74

It seems that it is never used, is it necessary or redundant?

**Comment by p-christ** [comment]
thanks, you are correct, it isn't necessary and i've removed it now
