### ISSUE TITLE
ModuleNotFoundError: No module named 'nn_builder'

### ISSUE THREAD

**Issue by BaiLiping** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#28]
was shown error message: 
ModuleNotFoundError: No module named 'nn_builder'

**Comment by p-christ** [comment]
have you downloaded the nn_builder package? 

Try doing: 

pip3 install nn_builder

in the command line

**Comment by BaiLiping** [comment]
OK, it works now
