### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by m1996** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#39]
hi.thanks a lot for sharing your code its very nice and clean and readable.
i want to run it in mountain car discrete environment, any suggestion for parameters or networks to get better results?
regards

**Comment by p-christ** [comment]
Not sure but maybe try the ones in the results/cart_pole.py file

**Comment by m1996** [comment]
Thanks for your reply, we have tried that but the result was not as good as cartpole(maybe because of harder exploration?)do you have any suggestion what should we do? Or how should we find best paramerers?

**Comment by p-christ** [comment]
Mmm yeah try increasing exploration by changing the
epsilon_decay_rate_denominator
