### ISSUE TITLE
Dqn problem

### ISSUE THREAD

**Issue by m1996** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#40]
Hi again
I've taken a look at your dqn algorithm, i've heard that dqn has 2 nets,one for q and one for target.but i cannot find your target network...where is it? Does it exist?
Regards

**Comment by p-christ** [comment]
See the DQN with fixed Q targets file

**Comment by m1996** [comment]
Thank you so much for your reply. we are newbies and eager for science:) would you please answer issue#39 too please?
