### ISSUE TITLE
Wrong temperature loss implementation for discrete SAC

### ISSUE THREAD

**Issue by qiyan98** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#61]
In the discrete-SAC paper, the temperature loss in Eq. (11) indicates that the direct expectation should be calculated rather than the Monte-carlo estimate, the same logic as Eq. (10). The implementation however, still calls the `calculate_entropy_tuning_loss` in `SAC.py` using `.mean()`.

**Comment by p-christ** [comment]
thanks, are you able to make a pull request fixing the issue and i can incorporate it?

**Comment by qiyan98** [comment]
Sorry, didn't notice that the expected log_pi is already calculated in the discrete SAC. So, the code should be just good.
